### ISSUE TITLE
fastify v3 | related to https://github.com/fastify/fastify/issues/2217 

### ISSUE THREAD

**Issue by x-077** [jsumners/fastify-server-session#10]
Hello, 

Just wondering if this plugin will have issues with the new fastify. I dont see it in the list [here](https://github.com/fastify/fastify/issues/2217). Do you plan to move it to `fastify` repository as an`official` plugin ?

Thanks.

**Comment by jsumners** [comment]
It should not have any issues with v3. But I do not intend to update it until v3 is fully released. If you'd like to submit a PR that does the updates to verify that, I'd appreciate it.

No, I do not intend to add it to the org as an official plugin.

**Comment by millette** [comment]
Close? Since [4.0.0](https://github.com/jsumners/fastify-server-session/releases/tag/v4.0.0) is out and <https://github.com/fastify/fastify/issues/2217> is done too.

**Comment by jsumners** [comment]
Yep. Thanks.
