### ISSUE TITLE
Destroy session from store (cache)

### ISSUE THREAD

**Issue by dbauszus-glx** [jsumners/fastify-server-session#2]
First of all. Massive thanks for this plugin. I finally get to store sessions in cache and be able to lookup the user object from the cookie.

I had a look at the source code and see where you set the session in the cache. I wonder whether it is possible to destroy/remove the session from the cache.

I am worried about the warning to not use cache as sessiont store in production and would like to implement a postgres session store. I have my ACL in postgres and would like to store the sessions themselves in the same database.

Do you know about any fastify implementation which uses a postgres session store instead of the mem cache?

I looked at the fastify-secure-session plugin but wasn't able to get this working at all.

**Comment by jsumners** [comment]
Easiest thing to do is set the session to ‘{}‘.

It wouldn’t be difficult to write an abstract-cache provider for Postgres. But I recommend using Redis instead. It’s a perfect fit for sessions.

**Comment by dbauszus-glx** [comment]
That works a treat. Thanks.

I will have a go at writing an abstract-cache provider later this year.

**Comment by dbauszus-glx** [comment]
Thinking about it. I probably will first have a play with the JWT support in fastify. This way I won't have to bother with session stores. Just ran into a problem where a client library uses fetch and I cannot make it use cookies. :(
