### ISSUE TITLE
[Question] Would it be correct way to logout user?

### ISSUE THREAD

**Issue by mandaputtra** [jsumners/fastify-server-session#9]
I'm not sure on how to logout user the right way. So after applying this package on server, server will send `sessionid` cookies to client. But is this the right way to logout? I'm not sure just set the session to `{}` would be okay. Or it is consider okay? since `sessionid` cookies are actually help to track the session?

```js
const fastify = require('fastify')()
fastify
  .register(require('fastify-cookie'))
  .register(require('fastify-caching'))
  .register(require('fastify-server-session'), {
    secretKey: 'some-secret-password-at-least-32-characters-long',
    sessionMaxAge: 900000, // 15 minutes in milliseconds
    cookie: {
      domain: '.example.com',
      path: '/'
    }
  })

fastify.get('/login', (req, reply) => {
  req.session.foo = 'the-secret-key-JWT-or-somehat-related-to-user'
  reply.send()
})

fastify.get('/logout', (req, reply) => {
req.session.foo = {}  
reply
    .setCookie('sessionid', 'invalid', {
       expires: 10,
       maxAge: new Date() // will set the expire to current date and time
    })
    .send('Youre loged out!')
})
```

[UPDATE]

Okay. I actually cant get `sessionid` using `req.cookies.sessionid` so `req.session.foo = {}` this would be correct way to logout user?

**Comment by jsumners** [comment]
Yes. If the session is empty then there is no data to make any comparison against to validate a "logged in" user. Therefore, the session is effectively invalidated.

**Comment by mandaputtra** [comment]
Okay thanks for your confirmation 👍
